apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 800
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  selector:
    matchLabels:
      app: hello-python
  replicas: 2
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 1
#       maxUnavailable: 1
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: flaskapp
        image: canelkatmis/flaskapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 800
        livenessProbe:
          httpGet:
            path: /alive
            port: 800
          initialDelaySeconds: 1
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 800
          initialDelaySeconds: 5
          periodSeconds: 15
